name: API Test Suite
on:
  workflow_dispatch:
jobs:
  api-tests:
    runs-on: ubuntu-latest    # or windows-latest, macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests
        run: mvn clean test -pl api-automation -am -Dparallel=methods -DthreadCount=3

      - name: Upload API Test Logs
        uses: actions/upload-artifact@v4
        with:
         name: api-test-logs
         path: |
           api-automation/target/logs/**
           api-automation/target/API_Test_Report.html